title = "Osprey Example Site"
baseURL = ""
tags = [ "portfolio", "web design", "blog" ]
languageCode = "en-US"
config = "config.toml"
theme = "osprey"
canonifyURLS = true
googleAnalytics = ""
disqusShortname = "tomanistor"
disableKinds = [ "taxonomy", "taxonomyTerm" ]
themesDir = "themes"
publishDir = "public"

[Params]
tagline = "Daniele Verzolini"
author = "Daniele Verzolini"
description = "Graphic Designer Freelance nella zona di Ancona"
logoBig = "/images/hugo.png"
logoSmall = "/images/hugo.png"
favicon = "favicon.ico"
opengraphImage = "/images/osprey.png"
email = "d.verzolini@gmail.com"
googleTagManger = ""
customCSS = false
twitter = "TomaNistor"
linkedin = "DanieleVerzolini"
github = "Dtime21"
facebook = ""
copyright = true
credit = false
cacheBustCSS = false
cacheBustJS = false
highlightJS = true
highlightJSStyle = ""
highlightJSScript = ""
ajaxFormspree = false
ajaxFormspreeGold = false
ajaxBasin = "https://usebasin.com/f/0eae7044d4c2"
lazyloading = true

[[menu.main]]
name = "About"
url = "/#about"
weight = 1

[[menu.main]]
name = "Work"
url = "/#work"
weight = 2


[[menu.main]]
name = "Contact"
url = "/#contact"
weight = 4
